//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Drako_Facturacion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        public int id { get; set; }
        public string names { get; set; }
        public string comercial_name { get; set; }
        public string RFC { get; set; }
        public string ResidenciaFiscal { get; set; }
        public string CP { get; set; }
        public string Domicilio { get; set; }
        public Nullable<int> idEstado { get; set; }
        public Nullable<int> idMunicipio { get; set; }
        public Nullable<int> idUser { get; set; }
        public Nullable<int> idState { get; set; }
    
        public virtual cstate cstate { get; set; }
        public virtual users users { get; set; }
    }
}
