//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Drako_Facturacion.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FacturacionEntities : DbContext
    {
        public FacturacionEntities()
            : base("name=FacturacionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<cstate> cstate { get; set; }
        public DbSet<cstate_factura> cstate_factura { get; set; }
        public DbSet<ctype_facturacion> ctype_facturacion { get; set; }
        public DbSet<customer> customer { get; set; }
        public DbSet<factura> factura { get; set; }
        public DbSet<product> product { get; set; }
        public DbSet<producto_tax> producto_tax { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<tax> tax { get; set; }
        public DbSet<users> users { get; set; }
    }
}
