//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Drako_Facturacion.Models.SAT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cat_Impuesto
    {
        public string Impuesto { get; set; }
        public string Descripcion { get; set; }
        public bool AplicaLocal { get; set; }
        public string Cuenta { get; set; }
    }
}
