//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Drako_Facturacion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ctype_facturacion
    {
        public ctype_facturacion()
        {
            this.factura = new HashSet<factura>();
        }
    
        public int id { get; set; }
        public string names { get; set; }
    
        public virtual ICollection<factura> factura { get; set; }
    }
}
