//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Drako_Facturacion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class factura
    {
        public int id { get; set; }
        public string UUID { get; set; }
        public string RFCReceptor { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string Serie { get; set; }
        public Nullable<int> Folio { get; set; }
        public Nullable<int> idUser { get; set; }
        public Nullable<int> idType { get; set; }
        public Nullable<System.DateTime> date_create { get; set; }
        public Nullable<int> idStateFacturacion { get; set; }
    
        public virtual ctype_facturacion ctype_facturacion { get; set; }
        public virtual users users { get; set; }
    }
}
