//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Drako_Facturacion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class producto_tax
    {
        public int id { get; set; }
        public Nullable<int> idProduct { get; set; }
        public Nullable<int> idtax { get; set; }
    
        public virtual product product { get; set; }
        public virtual tax tax { get; set; }
    }
}
