//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Drako_Facturacion.Models.SAT
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormasPago
    {
        public string IdFormaPago { get; set; }
        public string Descripcion { get; set; }
        public bool PideCta { get; set; }
        public string NoOperacion { get; set; }
        public string RFCEmisOrd { get; set; }
        public string CtaOrdenante { get; set; }
        public string PatronOrdenante { get; set; }
        public string RFCEmisBen { get; set; }
        public string CtaBeneficiario { get; set; }
        public string PatronBeneficiario { get; set; }
        public string TipoCadena { get; set; }
        public string NombreBanco { get; set; }
        public string CodeCXC { get; set; }
    }
}
