//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Drako_Facturacion.Models.SAT
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SATEntities : DbContext
    {
        public SATEntities()
            : base("name=SATEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Cat_Periodicidad> Cat_Periodicidad { get; set; }
        public DbSet<Cat_Regimen> Cat_Regimen { get; set; }
        public DbSet<Cat_TipoComp> Cat_TipoComp { get; set; }
        public DbSet<Cat_TipoContribuyente> Cat_TipoContribuyente { get; set; }
        public DbSet<Cat_UMedida> Cat_UMedida { get; set; }
        public DbSet<Cat_UsoCFDi> Cat_UsoCFDi { get; set; }
        public DbSet<Cat_Years> Cat_Years { get; set; }
        public DbSet<FormasPago> FormasPago { get; set; }
        public DbSet<Cat_MetodoPago> Cat_MetodoPago { get; set; }
        public DbSet<Cat_Pais> Cat_Pais { get; set; }
        public DbSet<Cat_TPagoRet> Cat_TPagoRet { get; set; }
        public DbSet<Cat_ClaveProdServ> Cat_ClaveProdServ { get; set; }
        public DbSet<Cat_CodigoPostal> Cat_CodigoPostal { get; set; }
        public DbSet<Cat_Exportacion> Cat_Exportacion { get; set; }
        public DbSet<Cat_Impuesto> Cat_Impuesto { get; set; }
        public DbSet<Cat_Meses> Cat_Meses { get; set; }
        public DbSet<Cat_Moneda> Cat_Moneda { get; set; }
        public DbSet<Cat_MotivoCancelacion> Cat_MotivoCancelacion { get; set; }
        public DbSet<Cat_TasaCuota> Cat_TasaCuota { get; set; }
        public DbSet<Cat_TRelacion> Cat_TRelacion { get; set; }
        public DbSet<Cat_TRetencion> Cat_TRetencion { get; set; }
        public DbSet<Cat_TipoCadenaPago> Cat_TipoCadenaPago { get; set; }
        public DbSet<Cat_TipoDivUtil> Cat_TipoDivUtil { get; set; }
    }
}
