//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Drako_Facturacion.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:ws_api", ConfigurationName="ServiceReference1.ServicioTimbradoWSPortType")]
    public interface ServicioTimbradoWSPortType {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ServicioTimbradoWS#consultarCFDI", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Drako_Facturacion.ServiceReference1.RespuestaConsultarCFDI consultarCFDI(string apikey, string uuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ServicioTimbradoWS#consultarCFDI", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<Drako_Facturacion.ServiceReference1.RespuestaConsultarCFDI> consultarCFDIAsync(string apikey, string uuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ServicioTimbradoWS#timbrar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Drako_Facturacion.ServiceReference1.RespuestaTimbrado timbrar(string apikey, string xmlCFDI);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ServicioTimbradoWS#timbrar", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<Drako_Facturacion.ServiceReference1.RespuestaTimbrado> timbrarAsync(string apikey, string xmlCFDI);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ServicioTimbradoWS#timbrar3", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Drako_Facturacion.ServiceReference1.RespuestaTimbrado timbrar3(string apikey, string xmlCFDI);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ServicioTimbradoWS#timbrar3", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<Drako_Facturacion.ServiceReference1.RespuestaTimbrado> timbrar3Async(string apikey, string xmlCFDI);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ServicioTimbradoWS#timbrar3", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Drako_Facturacion.ServiceReference1.RespuestaTimbrado timbrarTFD(string apikey, string xmlCFDI);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ServicioTimbradoWS#timbrar3", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<Drako_Facturacion.ServiceReference1.RespuestaTimbrado> timbrarTFDAsync(string apikey, string xmlCFDI);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ServicioTimbradoWS#timbrar3", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Drako_Facturacion.ServiceReference1.RespuestaTimbrado timbrarConSello(string apikey, string xmlCFDI, string keyPEM);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ServicioTimbradoWS#timbrar3", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<Drako_Facturacion.ServiceReference1.RespuestaTimbrado> timbrarConSelloAsync(string apikey, string xmlCFDI, string keyPEM);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ServicioTimbradoWS#timbrar3", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Drako_Facturacion.ServiceReference1.RespuestaTimbrado timbrarConSello3(string apikey, string xmlCFDI, string keyPEM);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ServicioTimbradoWS#timbrar3", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<Drako_Facturacion.ServiceReference1.RespuestaTimbrado> timbrarConSello3Async(string apikey, string xmlCFDI, string keyPEM);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ServicioTimbradoWS#timbrarJSON", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Drako_Facturacion.ServiceReference1.RespuestaTimbrado timbrarJSON(string apikey, string jsonB64, string keyPEM, string cerPEM);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ServicioTimbradoWS#timbrarJSON", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<Drako_Facturacion.ServiceReference1.RespuestaTimbrado> timbrarJSONAsync(string apikey, string jsonB64, string keyPEM, string cerPEM);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ServicioTimbradoWS#timbrarJSON2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Drako_Facturacion.ServiceReference1.RespuestaTimbrado timbrarJSON2(string apikey, string jsonB64, string keyPEM, string cerPEM, string plantilla);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ServicioTimbradoWS#timbrarJSON2", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<Drako_Facturacion.ServiceReference1.RespuestaTimbrado> timbrarJSON2Async(string apikey, string jsonB64, string keyPEM, string cerPEM, string plantilla);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ServicioTimbradoWS#timbrarJSON3", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Drako_Facturacion.ServiceReference1.RespuestaTimbrado timbrarJSON3(string apikey, string jsonB64, string keyPEM, string cerPEM);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ServicioTimbradoWS#timbrarJSON3", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<Drako_Facturacion.ServiceReference1.RespuestaTimbrado> timbrarJSON3Async(string apikey, string jsonB64, string keyPEM, string cerPEM);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ServicioTimbradoWS#timbrarTXT", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Drako_Facturacion.ServiceReference1.RespuestaTimbrado timbrarTXT(string apikey, string txtB64, string keyPEM, string cerPEM);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ServicioTimbradoWS#timbrarTXT", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<Drako_Facturacion.ServiceReference1.RespuestaTimbrado> timbrarTXTAsync(string apikey, string txtB64, string keyPEM, string cerPEM);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ServicioTimbradoWS#timbrarTXT2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Drako_Facturacion.ServiceReference1.RespuestaTimbrado timbrarTXT2(string apikey, string txtB64, string keyPEM, string cerPEM, string plantilla, string logoB64);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ServicioTimbradoWS#timbrarTXT2", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<Drako_Facturacion.ServiceReference1.RespuestaTimbrado> timbrarTXT2Async(string apikey, string txtB64, string keyPEM, string cerPEM, string plantilla, string logoB64);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ServicioTimbradoWS#timbrarTXT3", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Drako_Facturacion.ServiceReference1.RespuestaTimbrado timbrarTXT3(string apikey, string txtB64, string keyPEM, string cerPEM);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ServicioTimbradoWS#timbrarTXT3", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<Drako_Facturacion.ServiceReference1.RespuestaTimbrado> timbrarTXT3Async(string apikey, string txtB64, string keyPEM, string cerPEM);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ServicioTimbradoWS#cancelar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Drako_Facturacion.ServiceReference1.RespuestaCancelar cancelar(string apikey, string keyCSD, string cerCSD, string passCSD, string uuid, string rfcEmisor, string rfcReceptor, double total, string motivo, string folioSustitucion);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ServicioTimbradoWS#cancelar", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<Drako_Facturacion.ServiceReference1.RespuestaCancelar> cancelarAsync(string apikey, string keyCSD, string cerCSD, string passCSD, string uuid, string rfcEmisor, string rfcReceptor, double total, string motivo, string folioSustitucion);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ServicioTimbradoWS#cancelar2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Drako_Facturacion.ServiceReference1.RespuestaCancelar cancelar2(string apikey, string keyCSD, string cerCSD, string passCSD, string uuid, string rfcEmisor, string rfcReceptor, double total, string motivo, string folioSustitucion);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ServicioTimbradoWS#cancelar2", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<Drako_Facturacion.ServiceReference1.RespuestaCancelar> cancelar2Async(string apikey, string keyCSD, string cerCSD, string passCSD, string uuid, string rfcEmisor, string rfcReceptor, double total, string motivo, string folioSustitucion);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ServicioTimbradoWS#cancelarPFX", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Drako_Facturacion.ServiceReference1.RespuestaCancelar cancelarPFX(string apikey, string filePFX, string passPFX, string uuid, string rfcEmisor, string rfcReceptor, double total, string motivo, string folioSustitucion);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ServicioTimbradoWS#cancelarPFX", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<Drako_Facturacion.ServiceReference1.RespuestaCancelar> cancelarPFXAsync(string apikey, string filePFX, string passPFX, string uuid, string rfcEmisor, string rfcReceptor, double total, string motivo, string folioSustitucion);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ServicioTimbradoWS#cancelarPFX2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Drako_Facturacion.ServiceReference1.RespuestaCancelar cancelarPFX2(string apikey, string filePFX, string passPFX, string uuid, string rfcEmisor, string rfcReceptor, double total, string motivo, string folioSustitucion);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ServicioTimbradoWS#cancelarPFX2", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<Drako_Facturacion.ServiceReference1.RespuestaCancelar> cancelarPFX2Async(string apikey, string filePFX, string passPFX, string uuid, string rfcEmisor, string rfcReceptor, double total, string motivo, string folioSustitucion);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ServicioTimbradoWS#cancelarPEM", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Drako_Facturacion.ServiceReference1.RespuestaCancelar cancelarPEM(string apikey, string keyPEM, string cerPEM, string uuid, string rfcEmisor, string rfcReceptor, double total, string motivo, string folioSustitucion);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ServicioTimbradoWS#cancelarPEM", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<Drako_Facturacion.ServiceReference1.RespuestaCancelar> cancelarPEMAsync(string apikey, string keyPEM, string cerPEM, string uuid, string rfcEmisor, string rfcReceptor, double total, string motivo, string folioSustitucion);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ServicioTimbradoWS#consultarEstadoSAT", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Drako_Facturacion.ServiceReference1.RespuestaEstatusSAT consultarEstadoSAT(string apikey, string uuid, string rfcEmisor, string rfcReceptor, string total);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ServicioTimbradoWS#consultarEstadoSAT", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<Drako_Facturacion.ServiceReference1.RespuestaEstatusSAT> consultarEstadoSATAsync(string apikey, string uuid, string rfcEmisor, string rfcReceptor, string total);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ServicioTimbradoWS#consultarCreditosDisponibles", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Drako_Facturacion.ServiceReference1.RespuestaCreditos consultarCreditosDisponibles(string apikey);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ServicioTimbradoWS#consultarCreditosDisponibles", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<Drako_Facturacion.ServiceReference1.RespuestaCreditos> consultarCreditosDisponiblesAsync(string apikey);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ServicioTimbradoWS#consultarCfdisRelacionados", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Drako_Facturacion.ServiceReference1.RespuestaRelacionados consultarCfdisRelacionados(string apikey, string keyPEM, string cerPEM, string uuid, string rfcEmisor);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ServicioTimbradoWS#consultarCfdisRelacionados", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<Drako_Facturacion.ServiceReference1.RespuestaRelacionados> consultarCfdisRelacionadosAsync(string apikey, string keyPEM, string cerPEM, string uuid, string rfcEmisor);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ServicioTimbradoWS#consultarAutorizacionesPendientes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Drako_Facturacion.ServiceReference1.RespuestaPendientes consultarAutorizacionesPendientes(string apikey, string keyPEM, string cerPEM);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ServicioTimbradoWS#consultarAutorizacionesPendientes", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<Drako_Facturacion.ServiceReference1.RespuestaPendientes> consultarAutorizacionesPendientesAsync(string apikey, string keyPEM, string cerPEM);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ServicioTimbradoWS#autorizarCancelacion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Drako_Facturacion.ServiceReference1.RespuestaAutorizar autorizarCancelacion(string apikey, string keyPEM, string cerPEM, string uuid, string respuesta);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ServicioTimbradoWS#autorizarCancelacion", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<Drako_Facturacion.ServiceReference1.RespuestaAutorizar> autorizarCancelacionAsync(string apikey, string keyPEM, string cerPEM, string uuid, string respuesta);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ServicioTimbradoWS#timbrarRetencion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Drako_Facturacion.ServiceReference1.RespuestaTimbrado timbrarRetencion(string apikey, string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ServicioTimbradoWS#timbrarRetencion", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<Drako_Facturacion.ServiceReference1.RespuestaTimbrado> timbrarRetencionAsync(string apikey, string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ServicioTimbradoWS#timbrarRetencionTFD", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Drako_Facturacion.ServiceReference1.RespuestaTimbrado timbrarRetencionTFD(string apikey, string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ServicioTimbradoWS#timbrarRetencionTFD", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<Drako_Facturacion.ServiceReference1.RespuestaTimbrado> timbrarRetencionTFDAsync(string apikey, string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ServicioTimbradoWS#timbrarRetencionJSON", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Drako_Facturacion.ServiceReference1.RespuestaTimbrado timbrarRetencionJSON(string apikey, string jsonB64, string keyPEM, string cerPEM, string plantilla);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ServicioTimbradoWS#timbrarRetencionJSON", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<Drako_Facturacion.ServiceReference1.RespuestaTimbrado> timbrarRetencionJSONAsync(string apikey, string jsonB64, string keyPEM, string cerPEM, string plantilla);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ServicioTimbradoWS#cancelarRetencionCSD", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Drako_Facturacion.ServiceReference1.RespuestaCancelar cancelarRetencionCSD(string apikey, string keyCSD, string cerCSD, string passCSD, string rfcEmisor, string uuid, string motivo, string folioSustitucion);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ServicioTimbradoWS#cancelarRetencionCSD", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<Drako_Facturacion.ServiceReference1.RespuestaCancelar> cancelarRetencionCSDAsync(string apikey, string keyCSD, string cerCSD, string passCSD, string rfcEmisor, string uuid, string motivo, string folioSustitucion);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ServicioTimbradoWS#timbrarSP", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Drako_Facturacion.ServiceReference1.RespuestaTimbradoSP timbrarSP(string apikey, string xmlCFDI);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ServicioTimbradoWS#timbrarSP", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<Drako_Facturacion.ServiceReference1.RespuestaTimbradoSP> timbrarSPAsync(string apikey, string xmlCFDI);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ServicioTimbradoWS#cancelarSP", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Drako_Facturacion.ServiceReference1.RespuestaCancelar cancelarSP(string apikey, string rfcEmisor, string uuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ServicioTimbradoWS#cancelarSP", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<Drako_Facturacion.ServiceReference1.RespuestaCancelar> cancelarSPAsync(string apikey, string rfcEmisor, string uuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ServicioTimbradoWS#validar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Drako_Facturacion.ServiceReference1.RespuestaValidacion validar(string apikey, string xmlCFDI);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ServicioTimbradoWS#validar", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<Drako_Facturacion.ServiceReference1.RespuestaValidacion> validarAsync(string apikey, string xmlCFDI);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:ws_api")]
    public partial class RespuestaConsultarCFDI : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string messageField;
        
        private string dataField;
        
        /// <remarks/>
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        public string data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("data");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:ws_api")]
    public partial class RespuestaValidacion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string messageField;
        
        private string dataField;
        
        /// <remarks/>
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        public string data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("data");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:ws_api")]
    public partial class RespuestaTimbradoSP : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string messageField;
        
        private string dataField;
        
        /// <remarks/>
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        public string data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("data");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:ws_api")]
    public partial class RespuestaAutorizar : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string messageField;
        
        private string dataField;
        
        /// <remarks/>
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        public string data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("data");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:ws_api")]
    public partial class RespuestaPendientes : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string messageField;
        
        private string dataField;
        
        /// <remarks/>
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        public string data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("data");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:ws_api")]
    public partial class RespuestaRelacionados : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string messageField;
        
        private string dataField;
        
        /// <remarks/>
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        public string data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("data");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:ws_api")]
    public partial class RespuestaCreditos : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string messageField;
        
        private int dataField;
        
        /// <remarks/>
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        public int data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("data");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:ws_api")]
    public partial class RespuestaEstatusSAT : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoEstatusField;
        
        private string esCancelableField;
        
        private string estadoField;
        
        private string estatusCancelacionField;
        
        /// <remarks/>
        public string CodigoEstatus {
            get {
                return this.codigoEstatusField;
            }
            set {
                this.codigoEstatusField = value;
                this.RaisePropertyChanged("CodigoEstatus");
            }
        }
        
        /// <remarks/>
        public string EsCancelable {
            get {
                return this.esCancelableField;
            }
            set {
                this.esCancelableField = value;
                this.RaisePropertyChanged("EsCancelable");
            }
        }
        
        /// <remarks/>
        public string Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("Estado");
            }
        }
        
        /// <remarks/>
        public string EstatusCancelacion {
            get {
                return this.estatusCancelacionField;
            }
            set {
                this.estatusCancelacionField = value;
                this.RaisePropertyChanged("EstatusCancelacion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:ws_api")]
    public partial class RespuestaCancelar : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string messageField;
        
        private string dataField;
        
        private string statusField;
        
        /// <remarks/>
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        public string data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("data");
            }
        }
        
        /// <remarks/>
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:ws_api")]
    public partial class RespuestaTimbrado : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string messageField;
        
        private string dataField;
        
        /// <remarks/>
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        public string data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("data");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioTimbradoWSPortTypeChannel : Drako_Facturacion.ServiceReference1.ServicioTimbradoWSPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioTimbradoWSPortTypeClient : System.ServiceModel.ClientBase<Drako_Facturacion.ServiceReference1.ServicioTimbradoWSPortType>, Drako_Facturacion.ServiceReference1.ServicioTimbradoWSPortType {
        
        public ServicioTimbradoWSPortTypeClient() {
        }
        
        public ServicioTimbradoWSPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioTimbradoWSPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioTimbradoWSPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioTimbradoWSPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Drako_Facturacion.ServiceReference1.RespuestaConsultarCFDI consultarCFDI(string apikey, string uuid) {
            return base.Channel.consultarCFDI(apikey, uuid);
        }
        
        public System.Threading.Tasks.Task<Drako_Facturacion.ServiceReference1.RespuestaConsultarCFDI> consultarCFDIAsync(string apikey, string uuid) {
            return base.Channel.consultarCFDIAsync(apikey, uuid);
        }
        
        public Drako_Facturacion.ServiceReference1.RespuestaTimbrado timbrar(string apikey, string xmlCFDI) {
            return base.Channel.timbrar(apikey, xmlCFDI);
        }
        
        public System.Threading.Tasks.Task<Drako_Facturacion.ServiceReference1.RespuestaTimbrado> timbrarAsync(string apikey, string xmlCFDI) {
            return base.Channel.timbrarAsync(apikey, xmlCFDI);
        }
        
        public Drako_Facturacion.ServiceReference1.RespuestaTimbrado timbrar3(string apikey, string xmlCFDI) {
            return base.Channel.timbrar3(apikey, xmlCFDI);
        }
        
        public System.Threading.Tasks.Task<Drako_Facturacion.ServiceReference1.RespuestaTimbrado> timbrar3Async(string apikey, string xmlCFDI) {
            return base.Channel.timbrar3Async(apikey, xmlCFDI);
        }
        
        public Drako_Facturacion.ServiceReference1.RespuestaTimbrado timbrarTFD(string apikey, string xmlCFDI) {
            return base.Channel.timbrarTFD(apikey, xmlCFDI);
        }
        
        public System.Threading.Tasks.Task<Drako_Facturacion.ServiceReference1.RespuestaTimbrado> timbrarTFDAsync(string apikey, string xmlCFDI) {
            return base.Channel.timbrarTFDAsync(apikey, xmlCFDI);
        }
        
        public Drako_Facturacion.ServiceReference1.RespuestaTimbrado timbrarConSello(string apikey, string xmlCFDI, string keyPEM) {
            return base.Channel.timbrarConSello(apikey, xmlCFDI, keyPEM);
        }
        
        public System.Threading.Tasks.Task<Drako_Facturacion.ServiceReference1.RespuestaTimbrado> timbrarConSelloAsync(string apikey, string xmlCFDI, string keyPEM) {
            return base.Channel.timbrarConSelloAsync(apikey, xmlCFDI, keyPEM);
        }
        
        public Drako_Facturacion.ServiceReference1.RespuestaTimbrado timbrarConSello3(string apikey, string xmlCFDI, string keyPEM) {
            return base.Channel.timbrarConSello3(apikey, xmlCFDI, keyPEM);
        }
        
        public System.Threading.Tasks.Task<Drako_Facturacion.ServiceReference1.RespuestaTimbrado> timbrarConSello3Async(string apikey, string xmlCFDI, string keyPEM) {
            return base.Channel.timbrarConSello3Async(apikey, xmlCFDI, keyPEM);
        }
        
        public Drako_Facturacion.ServiceReference1.RespuestaTimbrado timbrarJSON(string apikey, string jsonB64, string keyPEM, string cerPEM) {
            return base.Channel.timbrarJSON(apikey, jsonB64, keyPEM, cerPEM);
        }
        
        public System.Threading.Tasks.Task<Drako_Facturacion.ServiceReference1.RespuestaTimbrado> timbrarJSONAsync(string apikey, string jsonB64, string keyPEM, string cerPEM) {
            return base.Channel.timbrarJSONAsync(apikey, jsonB64, keyPEM, cerPEM);
        }
        
        public Drako_Facturacion.ServiceReference1.RespuestaTimbrado timbrarJSON2(string apikey, string jsonB64, string keyPEM, string cerPEM, string plantilla) {
            return base.Channel.timbrarJSON2(apikey, jsonB64, keyPEM, cerPEM, plantilla);
        }
        
        public System.Threading.Tasks.Task<Drako_Facturacion.ServiceReference1.RespuestaTimbrado> timbrarJSON2Async(string apikey, string jsonB64, string keyPEM, string cerPEM, string plantilla) {
            return base.Channel.timbrarJSON2Async(apikey, jsonB64, keyPEM, cerPEM, plantilla);
        }
        
        public Drako_Facturacion.ServiceReference1.RespuestaTimbrado timbrarJSON3(string apikey, string jsonB64, string keyPEM, string cerPEM) {
            return base.Channel.timbrarJSON3(apikey, jsonB64, keyPEM, cerPEM);
        }
        
        public System.Threading.Tasks.Task<Drako_Facturacion.ServiceReference1.RespuestaTimbrado> timbrarJSON3Async(string apikey, string jsonB64, string keyPEM, string cerPEM) {
            return base.Channel.timbrarJSON3Async(apikey, jsonB64, keyPEM, cerPEM);
        }
        
        public Drako_Facturacion.ServiceReference1.RespuestaTimbrado timbrarTXT(string apikey, string txtB64, string keyPEM, string cerPEM) {
            return base.Channel.timbrarTXT(apikey, txtB64, keyPEM, cerPEM);
        }
        
        public System.Threading.Tasks.Task<Drako_Facturacion.ServiceReference1.RespuestaTimbrado> timbrarTXTAsync(string apikey, string txtB64, string keyPEM, string cerPEM) {
            return base.Channel.timbrarTXTAsync(apikey, txtB64, keyPEM, cerPEM);
        }
        
        public Drako_Facturacion.ServiceReference1.RespuestaTimbrado timbrarTXT2(string apikey, string txtB64, string keyPEM, string cerPEM, string plantilla, string logoB64) {
            return base.Channel.timbrarTXT2(apikey, txtB64, keyPEM, cerPEM, plantilla, logoB64);
        }
        
        public System.Threading.Tasks.Task<Drako_Facturacion.ServiceReference1.RespuestaTimbrado> timbrarTXT2Async(string apikey, string txtB64, string keyPEM, string cerPEM, string plantilla, string logoB64) {
            return base.Channel.timbrarTXT2Async(apikey, txtB64, keyPEM, cerPEM, plantilla, logoB64);
        }
        
        public Drako_Facturacion.ServiceReference1.RespuestaTimbrado timbrarTXT3(string apikey, string txtB64, string keyPEM, string cerPEM) {
            return base.Channel.timbrarTXT3(apikey, txtB64, keyPEM, cerPEM);
        }
        
        public System.Threading.Tasks.Task<Drako_Facturacion.ServiceReference1.RespuestaTimbrado> timbrarTXT3Async(string apikey, string txtB64, string keyPEM, string cerPEM) {
            return base.Channel.timbrarTXT3Async(apikey, txtB64, keyPEM, cerPEM);
        }
        
        public Drako_Facturacion.ServiceReference1.RespuestaCancelar cancelar(string apikey, string keyCSD, string cerCSD, string passCSD, string uuid, string rfcEmisor, string rfcReceptor, double total, string motivo, string folioSustitucion) {
            return base.Channel.cancelar(apikey, keyCSD, cerCSD, passCSD, uuid, rfcEmisor, rfcReceptor, total, motivo, folioSustitucion);
        }
        
        public System.Threading.Tasks.Task<Drako_Facturacion.ServiceReference1.RespuestaCancelar> cancelarAsync(string apikey, string keyCSD, string cerCSD, string passCSD, string uuid, string rfcEmisor, string rfcReceptor, double total, string motivo, string folioSustitucion) {
            return base.Channel.cancelarAsync(apikey, keyCSD, cerCSD, passCSD, uuid, rfcEmisor, rfcReceptor, total, motivo, folioSustitucion);
        }
        
        public Drako_Facturacion.ServiceReference1.RespuestaCancelar cancelar2(string apikey, string keyCSD, string cerCSD, string passCSD, string uuid, string rfcEmisor, string rfcReceptor, double total, string motivo, string folioSustitucion) {
            return base.Channel.cancelar2(apikey, keyCSD, cerCSD, passCSD, uuid, rfcEmisor, rfcReceptor, total, motivo, folioSustitucion);
        }
        
        public System.Threading.Tasks.Task<Drako_Facturacion.ServiceReference1.RespuestaCancelar> cancelar2Async(string apikey, string keyCSD, string cerCSD, string passCSD, string uuid, string rfcEmisor, string rfcReceptor, double total, string motivo, string folioSustitucion) {
            return base.Channel.cancelar2Async(apikey, keyCSD, cerCSD, passCSD, uuid, rfcEmisor, rfcReceptor, total, motivo, folioSustitucion);
        }
        
        public Drako_Facturacion.ServiceReference1.RespuestaCancelar cancelarPFX(string apikey, string filePFX, string passPFX, string uuid, string rfcEmisor, string rfcReceptor, double total, string motivo, string folioSustitucion) {
            return base.Channel.cancelarPFX(apikey, filePFX, passPFX, uuid, rfcEmisor, rfcReceptor, total, motivo, folioSustitucion);
        }
        
        public System.Threading.Tasks.Task<Drako_Facturacion.ServiceReference1.RespuestaCancelar> cancelarPFXAsync(string apikey, string filePFX, string passPFX, string uuid, string rfcEmisor, string rfcReceptor, double total, string motivo, string folioSustitucion) {
            return base.Channel.cancelarPFXAsync(apikey, filePFX, passPFX, uuid, rfcEmisor, rfcReceptor, total, motivo, folioSustitucion);
        }
        
        public Drako_Facturacion.ServiceReference1.RespuestaCancelar cancelarPFX2(string apikey, string filePFX, string passPFX, string uuid, string rfcEmisor, string rfcReceptor, double total, string motivo, string folioSustitucion) {
            return base.Channel.cancelarPFX2(apikey, filePFX, passPFX, uuid, rfcEmisor, rfcReceptor, total, motivo, folioSustitucion);
        }
        
        public System.Threading.Tasks.Task<Drako_Facturacion.ServiceReference1.RespuestaCancelar> cancelarPFX2Async(string apikey, string filePFX, string passPFX, string uuid, string rfcEmisor, string rfcReceptor, double total, string motivo, string folioSustitucion) {
            return base.Channel.cancelarPFX2Async(apikey, filePFX, passPFX, uuid, rfcEmisor, rfcReceptor, total, motivo, folioSustitucion);
        }
        
        public Drako_Facturacion.ServiceReference1.RespuestaCancelar cancelarPEM(string apikey, string keyPEM, string cerPEM, string uuid, string rfcEmisor, string rfcReceptor, double total, string motivo, string folioSustitucion) {
            return base.Channel.cancelarPEM(apikey, keyPEM, cerPEM, uuid, rfcEmisor, rfcReceptor, total, motivo, folioSustitucion);
        }
        
        public System.Threading.Tasks.Task<Drako_Facturacion.ServiceReference1.RespuestaCancelar> cancelarPEMAsync(string apikey, string keyPEM, string cerPEM, string uuid, string rfcEmisor, string rfcReceptor, double total, string motivo, string folioSustitucion) {
            return base.Channel.cancelarPEMAsync(apikey, keyPEM, cerPEM, uuid, rfcEmisor, rfcReceptor, total, motivo, folioSustitucion);
        }
        
        public Drako_Facturacion.ServiceReference1.RespuestaEstatusSAT consultarEstadoSAT(string apikey, string uuid, string rfcEmisor, string rfcReceptor, string total) {
            return base.Channel.consultarEstadoSAT(apikey, uuid, rfcEmisor, rfcReceptor, total);
        }
        
        public System.Threading.Tasks.Task<Drako_Facturacion.ServiceReference1.RespuestaEstatusSAT> consultarEstadoSATAsync(string apikey, string uuid, string rfcEmisor, string rfcReceptor, string total) {
            return base.Channel.consultarEstadoSATAsync(apikey, uuid, rfcEmisor, rfcReceptor, total);
        }
        
        public Drako_Facturacion.ServiceReference1.RespuestaCreditos consultarCreditosDisponibles(string apikey) {
            return base.Channel.consultarCreditosDisponibles(apikey);
        }
        
        public System.Threading.Tasks.Task<Drako_Facturacion.ServiceReference1.RespuestaCreditos> consultarCreditosDisponiblesAsync(string apikey) {
            return base.Channel.consultarCreditosDisponiblesAsync(apikey);
        }
        
        public Drako_Facturacion.ServiceReference1.RespuestaRelacionados consultarCfdisRelacionados(string apikey, string keyPEM, string cerPEM, string uuid, string rfcEmisor) {
            return base.Channel.consultarCfdisRelacionados(apikey, keyPEM, cerPEM, uuid, rfcEmisor);
        }
        
        public System.Threading.Tasks.Task<Drako_Facturacion.ServiceReference1.RespuestaRelacionados> consultarCfdisRelacionadosAsync(string apikey, string keyPEM, string cerPEM, string uuid, string rfcEmisor) {
            return base.Channel.consultarCfdisRelacionadosAsync(apikey, keyPEM, cerPEM, uuid, rfcEmisor);
        }
        
        public Drako_Facturacion.ServiceReference1.RespuestaPendientes consultarAutorizacionesPendientes(string apikey, string keyPEM, string cerPEM) {
            return base.Channel.consultarAutorizacionesPendientes(apikey, keyPEM, cerPEM);
        }
        
        public System.Threading.Tasks.Task<Drako_Facturacion.ServiceReference1.RespuestaPendientes> consultarAutorizacionesPendientesAsync(string apikey, string keyPEM, string cerPEM) {
            return base.Channel.consultarAutorizacionesPendientesAsync(apikey, keyPEM, cerPEM);
        }
        
        public Drako_Facturacion.ServiceReference1.RespuestaAutorizar autorizarCancelacion(string apikey, string keyPEM, string cerPEM, string uuid, string respuesta) {
            return base.Channel.autorizarCancelacion(apikey, keyPEM, cerPEM, uuid, respuesta);
        }
        
        public System.Threading.Tasks.Task<Drako_Facturacion.ServiceReference1.RespuestaAutorizar> autorizarCancelacionAsync(string apikey, string keyPEM, string cerPEM, string uuid, string respuesta) {
            return base.Channel.autorizarCancelacionAsync(apikey, keyPEM, cerPEM, uuid, respuesta);
        }
        
        public Drako_Facturacion.ServiceReference1.RespuestaTimbrado timbrarRetencion(string apikey, string xml) {
            return base.Channel.timbrarRetencion(apikey, xml);
        }
        
        public System.Threading.Tasks.Task<Drako_Facturacion.ServiceReference1.RespuestaTimbrado> timbrarRetencionAsync(string apikey, string xml) {
            return base.Channel.timbrarRetencionAsync(apikey, xml);
        }
        
        public Drako_Facturacion.ServiceReference1.RespuestaTimbrado timbrarRetencionTFD(string apikey, string xml) {
            return base.Channel.timbrarRetencionTFD(apikey, xml);
        }
        
        public System.Threading.Tasks.Task<Drako_Facturacion.ServiceReference1.RespuestaTimbrado> timbrarRetencionTFDAsync(string apikey, string xml) {
            return base.Channel.timbrarRetencionTFDAsync(apikey, xml);
        }
        
        public Drako_Facturacion.ServiceReference1.RespuestaTimbrado timbrarRetencionJSON(string apikey, string jsonB64, string keyPEM, string cerPEM, string plantilla) {
            return base.Channel.timbrarRetencionJSON(apikey, jsonB64, keyPEM, cerPEM, plantilla);
        }
        
        public System.Threading.Tasks.Task<Drako_Facturacion.ServiceReference1.RespuestaTimbrado> timbrarRetencionJSONAsync(string apikey, string jsonB64, string keyPEM, string cerPEM, string plantilla) {
            return base.Channel.timbrarRetencionJSONAsync(apikey, jsonB64, keyPEM, cerPEM, plantilla);
        }
        
        public Drako_Facturacion.ServiceReference1.RespuestaCancelar cancelarRetencionCSD(string apikey, string keyCSD, string cerCSD, string passCSD, string rfcEmisor, string uuid, string motivo, string folioSustitucion) {
            return base.Channel.cancelarRetencionCSD(apikey, keyCSD, cerCSD, passCSD, rfcEmisor, uuid, motivo, folioSustitucion);
        }
        
        public System.Threading.Tasks.Task<Drako_Facturacion.ServiceReference1.RespuestaCancelar> cancelarRetencionCSDAsync(string apikey, string keyCSD, string cerCSD, string passCSD, string rfcEmisor, string uuid, string motivo, string folioSustitucion) {
            return base.Channel.cancelarRetencionCSDAsync(apikey, keyCSD, cerCSD, passCSD, rfcEmisor, uuid, motivo, folioSustitucion);
        }
        
        public Drako_Facturacion.ServiceReference1.RespuestaTimbradoSP timbrarSP(string apikey, string xmlCFDI) {
            return base.Channel.timbrarSP(apikey, xmlCFDI);
        }
        
        public System.Threading.Tasks.Task<Drako_Facturacion.ServiceReference1.RespuestaTimbradoSP> timbrarSPAsync(string apikey, string xmlCFDI) {
            return base.Channel.timbrarSPAsync(apikey, xmlCFDI);
        }
        
        public Drako_Facturacion.ServiceReference1.RespuestaCancelar cancelarSP(string apikey, string rfcEmisor, string uuid) {
            return base.Channel.cancelarSP(apikey, rfcEmisor, uuid);
        }
        
        public System.Threading.Tasks.Task<Drako_Facturacion.ServiceReference1.RespuestaCancelar> cancelarSPAsync(string apikey, string rfcEmisor, string uuid) {
            return base.Channel.cancelarSPAsync(apikey, rfcEmisor, uuid);
        }
        
        public Drako_Facturacion.ServiceReference1.RespuestaValidacion validar(string apikey, string xmlCFDI) {
            return base.Channel.validar(apikey, xmlCFDI);
        }
        
        public System.Threading.Tasks.Task<Drako_Facturacion.ServiceReference1.RespuestaValidacion> validarAsync(string apikey, string xmlCFDI) {
            return base.Channel.validarAsync(apikey, xmlCFDI);
        }
    }
}
